### ISSUE TITLE
Permission Templates to publish on Video Portal: Make it possible to define multiple roles that get set with a template

### ISSUE THREAD

**Issue by dagraf** [opencast-ilias/OpenCast#68] opened 2022-08-17 13:52 UTC
**Description**
In the configuration of the plugin: in the tab "Video Portal" different permission templates can get created and a default template can be chosen. With those templates it is at the moment only possible to configure ONE single role with additional ACL actions that will be set when a series gets created or edited (see the series setting "Publish Series on VIDEOPORTAL"). This limits the possibilities of these templates, for example if for some uses cases additional roles should be set. In the case of the University of Bern we need to set an additional role in order to give logged in users the right to open a video in the Annotation Tool.

**Possible solution**
Please make it possible to add one or multiple additional role(s) when configuring the permission templates. All additional roles should NOT be mandatory and should have the same options as the first role (Read, Write, Additional ACL Actions, Aditional Actions with active Download, Additional Actions with active Annotate).

_Location_
In the tab "Video Portal" and there in the subtab "Permission Templates": When clicking on "Add New Template" or "Actions" > "Edit" at the very bottom of the form (below "Addtional Actions with active Annotate")

![Bildschirmfoto 2022-08-17 um 15 36 40](https://user-images.githubusercontent.com/15246287/185148047-5f3e6da9-8837-4f5d-8f3e-67d776da5329.png)

_Title:_
DE: Zusätzliche Rolle
EN: Additional role

_Description:_
DE: Rolle, welche in Opencast gesetzt wird (zusätzlich zu der ersten definitierten Rolle, nicht verpflichtend).
EN: Defines the role which will be set in Opencast (in addition to the role above, not mandatory).

**Comment by reiferschris** [comment] 2022-09-07 08:32
This seems like a partial duplicate of this feature request https://github.com/opencast-ilias/OpenCast/issues/15 

- Would it be possible to use the permission templates that can be configured in opencast instead of defining them in the plugin? They could be retrieved from this endpoint: `acl-manager/acl/acls.json` e.g.: https://stable.opencast.org/acl-manager/acl/acls.json
- It is a bit harder but maybe also a more flexible if ilias language variables are used instead of defining translations in the config? There could potentially be a lot more than two languages.

I would suggest to talk about this in the next community-meeting. :)

**Comment by dagraf** [comment] 2022-09-07 09:17
Thanks for the hint to feature request #15. I did not have it on my radar. And yes, lets talk about this in the next community-meeting. I will set it on the agenda. Meanwhile, you could maybe specify the feature request #15

**Closed** 2022-12-13 08:17 UTC
Labels: enhancement
