### ISSUE TITLE
Can not create a new Series

### ISSUE THREAD

**Issue by mic-men** [opencast-ilias/OpenCast#132] opened 2023-01-25 15:42 UTC
**Update from 7.3.2023:** Bug is fixed, still missing is the implementation of some specification (see comment https://github.com/opencast-ilias/OpenCast/issues/132#issuecomment-1408906808)

**Describe the bug**
A new series can not be created.
(Video upload and playing in existing series is possible with no problems.)

**To Reproduce**
 Try to create new Opencast Series in ILIAS (Existing Series: no)
 The error occurs independently of set metadata like mentioned in #131 .
The error occurs appearently in the plugin  before a creation is tried in Opencast.
In ILIAS remains an empty non-accessible Opencast series object which can not be deleted!

**Log**
Error thrown with message "Call to a member function addToAcls() on null"

Stacktrace:
#10 Error in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilObjOpenCastGUI.php:422
#9 ilObjOpenCastGUI:afterSave in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/Object/classes/class.ilObjectGUI.php:1032
#8 ilObjectGUI:saveObject in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilObjOpenCastGUI.php:368
#7 ilObjOpenCastGUI:save in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/Repository/classes/class.ilObjectPluginGUI.php:149
#6 ilObjectPluginGUI:executeCommand in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilObjOpenCastGUI.php:196
#5 ilObjOpenCastGUI:executeCommand in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/UICore/classes/class.ilCtrl.php:217
#4 ilCtrl:forwardCommand in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/Repository/classes/class.ilRepositoryGUI.php:375
#3 ilRepositoryGUI:show in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/Repository/classes/class.ilRepositoryGUI.php:337
#2 ilRepositoryGUI:executeCommand in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/UICore/classes/class.ilCtrl.php:217
#1 ilCtrl:forwardCommand in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/UICore/classes/class.ilCtrl.php:178
#0 ilCtrl:callBaseClass in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/ilias.php:23

**Environment (please complete the following information):**
 - ILIAS version: ILIAS (v7.16 2022-11-24) 
 - PHP version: PHP 7.4.3
 - Plugin version: 5.1.0
 - Opencast version: 10.13.0
 - Browser: Firefox
 - Only the basic OpenCast Plugin is used, nothing else (like Events).

**Comment by okaufman** [comment] 2023-01-25 15:58
Hello I have a question.
In the Plugin-Config under "Video Portal" -> "Permission Templates" 
Do you have any Templates configured? Is one Template selected as the default template?

**Comment by mic-men** [comment] 2023-01-25 17:46
Yes there are templates configured. Honestly I dont'know who had done this. In our main system still running the old plugin, there are no such templates.
The template configuration looks like this:
1.
Titel: Zugriff für alle authentifizierten Nutzer ueber AAI
Rolle: ROLE_USER
Leserechte: yes ; Schreibrechte: No
All other columns: nothing
2.
Titel: Anonymer Zugriff
Rolle: ROLE_ANONYMOUS
Leserechte: yes ; Schreibrechte: No
All other columns: nothing

None of them is set as default.
When I change this and set 1. as default, it's working! A series can be created!

Question: What is the effect  of this setting?
Should I set the write permission to yes? What would be the effect of that?
Or are the template settings a mistake at all?
I need to understand this - if the templates are needed I may have to add them on our plugin in the main ILIAS.
Thanks for clarification.

**Comment by ckozianka** [comment] 2023-01-26 10:02
Hi, we are experiencing the same problem. And we have no permission templates for video portal configured because we have no video portal.
Best regards
Carsten

**Comment by okaufman** [comment] 2023-01-30 15:39
Hello
Right now the plugin only works, if you have at least one template configured and set as default. This is a bug and we will work on it. 

Right know as a workaround, you can create a template and set it as default. You have to give the template a name and a role. The role can be anything. You just don't add any permissions for that role.

**Comment by dagraf** [comment] 2023-01-30 16:12
When taking care of this bug please consider:
At the moment the 'default template' does not get shown when the option "Publish Series on Video Portal" gets activated when creating a series. This leads to the fact, that if you only configure one default template (because the current state of the plugins forces you to do so) the option "Publish Series on Video Portal" is empty when it gets activated during the creation of a series (see screenhsot).

<img width="1652" alt="Bildschirmfoto 2023-01-30 um 16 52 27" src="https://user-images.githubusercontent.com/15246287/215527483-07a40868-285a-4f46-a9c1-8cdfb2133228.png">

Expected behavior:
- The default template does not get shown. This is allready the case.
- If only a default template is configured the option "Publish Series on Video Portal" does NOT get offered while creating and editing series.
- In plugin config: 
  - In the subtab "Permission Templates" change the description below the title "Permission Templates" to: "The created templates can be chosen from when creating or editing a series which need to be published to the video portal. Exception: The default template can not be chosen because it gets set if the series should NOT be published to the video portal. If chosen, the configured role with the given permissions and actions will be set on the series. The roles of the residual templates will be removed."
  - Change the description of the setting "Default Template" to: "This template will be used if the series should NOT be published to the external video portal. Therefore, only one template can be defined as the default template. This template does not get offered when creating or editing series."
  - C
-

**Comment by ckozianka** [comment] 2023-01-31 09:37
Hi, your workaround works, thank you very much.

BTW: On our installation the template checkbox is displayed...
![Unbenannt](https://user-images.githubusercontent.com/18744789/215723205-76d66fe1-ca37-46a5-b5ce-7bb9263d94dd.png)

Kind regards
Carsten

**Comment by ckozianka** [comment] 2023-01-31 09:41
Checking it during creation of the series has no effect and does not get stored. Checking it inan existing OC object leads to "Error when communicating with Opencast server".

**Comment by dagraf** [comment] 2023-02-02 15:55
> Checking it during creation of the series has no effect and it does not get stored. Checking it in an existing OC object leads to "Error when communicating with Opencast server".

Could the latter be due to the bug described here https://github.com/opencast-ilias/OpenCast/issues/131? We were able to solve this with UNchecking the option "Read-Only" in the fields for "creator" and "contributer" (see subtab "Series" in the new tab "Metadata").

**Comment by dagraf** [comment] 2023-02-22 16:57
Thx for the fix, the bug does not exist anymore. I leave it open as the specifications mentioned in [this comment](https://github.com/opencast-ilias/OpenCast/issues/132#issuecomment-1408906808) are not yet implemented. This will follow later.

**Comment by dagraf** [comment] 2023-03-29 07:12
I created a new ticket containing the specifications of [this comment](https://github.com/opencast-ilias/OpenCast/issues/132#issuecomment-1408906808). Therefore, I close this ticket.

**Closed by dagraf** 2023-03-29 07:12 UTC
Labels: bug
