### ISSUE TITLE
Owner of an Opencast series always has download rights

### ISSUE THREAD

**Issue by snoesberger** [opencast-ilias/OpenCast#356] opened 2024-09-06 08:17 UTC
**Describe the bug**
The download button is always visible to the owner of the Opencast series, even if the 'Download' checkbox is disabled for 'Course Administrators' in the 'Rights' tab.

**To Reproduce**
1. Go to the 'Rights' tab of an Opencast series
2. Deactivate the 'Download' checkbox for 'Course Administrators'
3. As owner of the Opencast series go to the videos of the series
4. The download button is still visible

**Expected behavior**
The 'Download' checkbox for 'Course Administrators' in the 'Rights' section should also be effective for series owners.

**Environment (please complete the following information):**
- ILIAS version: v8.14 2024-08-13
- Plugin version: 8.1.4
- Opencast version: 15

**Comment by chfsx** [comment] 2024-11-04 19:44
The problem is the following: In ILIAS, the owner of an object always has all rights and these cannot be revoked. You can track this with any right, the “Permissions of User” tab in the rights tab is also helpful. The user is therefore not only the course admin, but also the “owner”.

@dagraf FYI

**Comment by dagraf** [comment] 2024-11-05 07:36
@chfsx If I understand you correctly, this is not a bug but a feature of ILIAS and can not be changed? If so, please close this issue.

**Comment by reiferschris** [comment] 2024-11-05 07:38
I'm not entirely sure everyone talks about the same owner? I suspect the issue had the ROLE_OWNER_{IDENTIFIER} in mind and not the "owner" of the ilias object?

**Comment by chfsx** [comment] 2024-11-05 07:42
@reiferschris thanks for asking the right questions :-) which owner is meant exactly? I can reproduce the issue described above with the ILIAS owner.

@dagraf yes we can close the issue if it's the ILIAS owner, since we cannot change this concept. if it's the ROLE_OWNER_{IDENTIFIER} we could try to fix that, but I assume the ILIAS owner then still would lead to the same issue since the ILIAS owner and the opencast owner is the same in most cases, right?

**Comment by dagraf** [comment] 2024-11-05 07:47
I'm speaking of the ILIAS owner who is indicated in the subtab "Owner" (see screenshot). Therefore, I close this issue. 

<img width="963" alt="Bildschirmfoto 2024-11-05 um 08 48 01" src="https://github.com/user-attachments/assets/6129810d-8bfa-481b-a4a7-5fb7a4da6c9f">

**Comment by dagraf** [comment] 2024-11-05 07:48
Closed.

**Closed as not planned by dagraf** 2024-11-05 07:48 UTC
Labels: bug, ILIAS 8
