### ISSUE TITLE
Release 8: error when adding new series object to a course with prefilled metadata

### ISSUE THREAD

**Issue by ferishili** [opencast-ilias/OpenCast#263] opened 2024-03-28 08:36 UTC
**Describe the bug**
When you add prefill placeholders to series metadata and try to add a series object to a course, a fatal error occurs stating that `str_replace` must always get string values!

**To Reproduce**
1. Have a clean installation of release_8 with PHP 8!
2. Go to Plugin Configs > Metadata > Series
3. Try to add prefill to the title with: `[COURSE.REF_ID]`
4. Save changes.
5. Go to a course and try to add a new Opencast Series Object.
6. See the error!

**Expected behavior**
Prefill must be working in any cases!

**Log**
```
[b128o] [2024-03-28 08:16:28.778737] ilias_8_root.ERROR: Whoops\Handler\CallbackHandler::handle:398 0 str_replace(): Argument #2 ($replace) must be of type array|string, int given in /release_8/src/Model/Metadata/Helper/MDPrefiller.php:207#0 /release_8/src/Model/Metadata/Helper/MDPrefiller.php(207): str_replace('[COURSE.REF_ID]', 83, 'Opencast Test C...')
#1 /release_8/src/UI/Metadata/MDFormItemBuilder.php(109): srag\Plugins\Opencast\Model\Metadata\Helper\MDPrefiller->getReplacedPrefill('[COURSE.TITLE] ...')
```

**Environment (please complete the following information):**
 - ILIAS version: v8.10
 - PHP version: 8.0.30
 - Plugin version: release_8
 - Opencast version 15.3
 - Browser: Firefox

**Additional context**
Did not check for release_7, however I think this is a PHP 8 strict error handler that causes the fatal error!

**Comment by dagraf** [comment] 2024-04-03 06:58
Thx for the bugreport. I can reproduce it on our ILIAS8 installation. It does not appear on our ILIAS7 installation. Therefore, it seems to be an issue only for release_8. 
I will test the bugfix soon.

**Comment by dagraf** [comment] 2024-04-09 12:44
After deploying https://github.com/opencast-ilias/OpenCast/pull/264 the bug does not appear anymore. I therefore close this issue.

**Closed as completed by dagraf** 2024-04-09 12:44 UTC
Labels: bug
