### ISSUE TITLE
Unable to create new Opencast repository objects with current V. 4.0.0 (main)

### ISSUE THREAD

**Issue by DZenker** [opencast-ilias/OpenCast#21] opened 2022-04-26 10:22 UTC
After we have installed the Opencast plugin in the latest version 4.0.0 , no new Opencast objects can be created anymore, as the following error always occurs:
_Whoops\Exception\ErrorException thrown with message "strlen() expects parameter 1 to be string, object given".
Stacktrace:
#14 Whoops\Exception\ErrorException in /srv/www/ilias.ludwig-fresenius.de/ilias/Customising/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Model/Group/Group.php:68
#13 strlen in /srv/www/ilias.ludwig-fresenius.de/ilias/Customizing/global/plugins/Services/RepositoryObject/OpenCast/src/Model/Group/Group.php:68
..._

This bug seems to be introduced with the changes made by the "origin/fix/2-workflow-parameter-load' fix and affects the main branch. Here are the corresponding code changes in src/Model/Group/Group.php:
```
        $data = json_decode(xoctRequest::root()->groups($this->getIdentifier())->get());
+        if(strlen($data) > 0) {
+            $this->loadFromStdClass($data);
+        }
```

**Comment by reiferschris** [comment] 2022-04-28 11:08
Hi, I can't reproduce the error with the slightly newer version 4.0.1, could you try if that version works for you? I do however have other slightly similar issues which differ do not occur in some environments.  See https://github.com/opencast-ilias/OpenCast/issues/24
Could you tell us some details about your setup?

**Comment by DZenker** [comment] 2022-04-28 11:36
Hi,

in our setup, this problem also occurs with the most recent version 4.0.1 (all versions that include the "[[origin/fix/2-workflow-parameter-laden](https://github.com/fluxapps/OpenCast/commit/9ae10e3ea7798290f73b4f674af27ee4efc8248f)" fix are affected). Yesterday, I patched the Group.php by removing the _if(strlen($data) > 0_) {} block for testing, and after that it worked without problems. Thus, this issue is definitely caused by applying a string function on an object (_strlen($data)_).

Our setup is: ILIAS V 7.7 with Opencast 10.10, PHP version is 7.4.3

**Comment by ebbertd** [comment] 2022-04-28 11:41
With which user are you testing this? root or an actual user account?

**Comment by DZenker** [comment] 2022-04-28 11:55
Both with a restricted test user, and also with an admin user.

**Comment by ebbertd** [comment] 2022-04-29 06:48
Given that we have similar environments and the plugin works for us but not for you, I suspect a difference in configuration might be the source of the error. Could you share your configuration? Of course without any secrets.

**Comment by DZenker** [comment] 2022-04-29 07:17
Here it is:

![ILIAS-Plugin-OpenCast - API](https://user-images.githubusercontent.com/5229751/165900229-c634dd02-ad6d-4433-b3e2-5822757f4bb1.png)
![ILIAS-Plugin-OpenCast - Aufzeichnungen](https://user-images.githubusercontent.com/5229751/165900256-7239eeec-68a5-491c-a699-db3a548e671e.png)
![ILIAS-Plugin-OpenCast - Gruppen Rollen](https://user-images.githubusercontent.com/5229751/165900269-6e6ba954-1155-44a5-982c-1b9240249f15.png)
![ILIAS-Plugin-OpenCast - Erweitert](https://user-images.githubusercontent.com/5229751/165900286-b2885ae6-93fc-4aa9-9733-42f6186855d7.png)
![ILIAS-Plugin-OpenCast - Workflow Parameter](https://user-images.githubusercontent.com/5229751/165900328-7fa8a77f-f1fa-435c-a90c-6ec49d041245.png)
![ILIAS-Plugin-OpenCast - Workflows](https://user-images.githubusercontent.com/5229751/165900330-70bf8424-f32b-42fb-bc2c-62164d0c8c75.png)
![ILIAS-Plugin-OpenCast - Metadaten Aufzeichnungen](https://user-images.githubusercontent.com/5229751/165900331-7337230f-5164-4e43-9224-a60668c5e9fd.png)
![ILIAS-Plugin-OpenCast - Metadaten Serien](https://user-images.githubusercontent.com/5229751/165900334-98157340-977d-4069-8723-d504bb6f8e49.png)
![ILIAS-Plugin-OpenCast - Player](https://user-images.githubusercontent.com/5229751/165900337-25d79d45-e84e-4f71-91d3-35bc5ca33a17.png)

**Comment by okaufman** [comment] 2022-04-29 10:46
I created a pull request.
Please check if the solution in the pr would work for you
https://github.com/opencast-ilias/OpenCast/pull/26

**Comment by DZenker** [comment] 2022-04-29 13:28
Hi,
yes, I can confirm that this works!

**Comment by Amstutz** [comment] 2022-05-02 08:38
The PR of @okaufman has been merged. Thx @okaufman for fixing and @DZenker for reporting and testing!

**Closed** 2022-05-02 08:40 UTC
